"""add_cascade_delete

Revision ID: 5075ba46df8e
Revises: ee7c67b0c920
Create Date: 2026-07-29 18:37:00.254641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5075ba46df8e'
down_revision: Union[str, None] = 'ee7c67b0c920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_files', schema=None) as batch_op:
        batch_op.drop_constraint('conversation_files_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('conversation_files_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_files', schema=None) as batch_op:
        batch_op.drop_constraint('conversation_files_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('conversation_files_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
